SocialChallenge/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using SocialChallenge.Methods;

using Data;
using Data.DataForms;
using static Data.Constants;

// Data Access libraries
using static DataLibrary.Logic.TaskProcessor;
using static DataLibrary.Logic.TeamProcessor;

// Main model
using TaskModel = Data.DataForms.Task;
using TeamModel = Data.DataForms.Team;

// Client model
using ClientTaskModel = Data.CreateForms.Task;

namespace SocialChallenge.Controllers
{
    public class TaskController : BaseController
    {
        #region Index
        // GET: Task/Index
        public ActionResult Index()
        {
            if (!UserSession.IsLoggedIn() || UserSession.GetAccessLevel() == AccessLevel.Normal)
            {
                ErrorMessage = "Je bent niet bevoegd voor deze pagina.";
                return RedirectToAction("Index", "Home");
            }

            List<TeamModel> teams = new List<TeamModel>();

            try
            {
                teams = LoadTeams();
            }
            catch (Exception exception)
            {
                ErrorMessage = $"Something went wrong receiving all teams. {exception.Message}";
            }

            return View(teams);
        }
        #endregion

        #region Create
        // GET: Task/Create
        public ActionResult Create(int id)
        {
            if (!UserSession.IsLoggedIn())
            {
                ErrorMessage = "Je moet ingelogd zijn om een team aan te kunnen passen!";
                return RedirectToAction("Index", "Team");
            }

            if (UserSession.GetAccessLevel() != AccessLevel.Normal)
            {
                ErrorMessage = "Alleen leerlingen mogen taken aanmaken.";
                return RedirectToAction("Index", "Team");
            }

            if (UserSession.GetTeamId() != id)
            {
                ErrorMessage = "Je mag alleen taken voor je eigen team aanmaken!";
                return RedirectToAction("Index", "Team");
            }

            return View();
        }

        // POST: Task/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ClientTaskModel task)
        {
            if (!ModelState.IsValid)
            {
                ErrorMessage = "Form is niet geldig";
                return View();
            }

            try
            {
                CreateTask((int)UserSession.GetTeamId(), task.Name, task.Description);
            }
            catch (Exception exception)
            {
                ErrorMessage = $"Something went wrong updating the new team. {exception.Message}";
                return View();
            }

            SuccessMessage = "Taak aangemaakt. Succes!";
            return RedirectToAction("Details", "Team", new { id = UserSession.GetTeamId() });
        }
        #endregion

        #region Approve / reject / revert
        // GET: Team/id/appove/taskid
        public ActionResult Approve(int id, int taskid)
        {
            if (!TaskApprovalHandler(taskid, Constants.TaskStatus.Approved))
            {
                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("Details", "Team", new { id });
        }

        // GET: Team/id/reject/taskid
        public ActionResult Reject(int id, int taskid)
        {
            if (!TaskApprovalHandler(taskid, Constants.TaskStatus.Rejected))
            {
                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("Details", "Team", new { id });
        }

        // GET: Team/id/reject/taskid
        public ActionResult Revert(int id, int taskid)
        {
            if (!TaskApprovalHandler(taskid, Constants.TaskStatus.New))
            {
                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("Details", "Team", new { id });
        }

        private bool TaskApprovalHandler(int taskid, Constants.TaskStatus status)
        {
            // User must be logged in for this action
            if (!UserSession.IsLoggedIn())
            {
                ErrorMessage = "Je moet ingelogd zijn voor deze actie!";
                return false;
            }

            // User must be a teacher or admin
            if (UserSession.GetAccessLevel() == AccessLevel.Normal)
            {
                ErrorMessage = "Je bent onbevoegd voor deze actie!";
                return false;
            }

            // Check if we are allowed to update the task
            TaskModel task = new TaskModel();
            task = GetTasksById(taskid);

            if (task.Approved == status)
            {
                ErrorMessage = $@"Deze taak staat al op status ""{status}""!";
                return true;
            }

            if (task.Done == TaskProgress.Open && status == Constants.TaskStatus.Approved)
            {
                ErrorMessage = "Deze taak is not niet volbracht door het team en mag nog niet goedgekeurd worden!";
                return true;
            }

            try
            {
                SetTaskApprovalById(taskid, status);
            }
            catch (Exception exception)
            {
                ErrorMessage = $"Something went wrong reverting the task. {exception.Message}";
                return true;
            }

            SuccessMessage = $"Taak is {(status == Constants.TaskStatus.New ? "teruggezet" : status == Constants.TaskStatus.Approved ? "goedgekeurd" : "afgekeurd")}.";
            return true;
        }
        #endregion

        #region Edit
        // GET: Team/id/Edit/taskid
        public ActionResult Edit(int id, int? taskid)
        {
            // User must be logged in
            if (!UserSession.IsLoggedIn())
            {
                ErrorMessage = "U moet ingelogd zijn om een taak aan te passen!";
                return RedirectToAction("Index", "Home");
            }

            User user = Session["user"] as User;

            // Tasks may only be edited by those in that team
            if (UserSession.GetAccessLevel() != AccessLevel.Normal || user.TeamId != id)
            {
                ErrorMessage = "Alleen teamleden mogen hun taken aanpassen!";
                return RedirectToAction("Index", "Team");
            }

            if (taskid == null)
            {
                ErrorMessage = "Er is een taaknummer nodig om op te zoeken!";
                return RedirectToAction("Details", "Team", new { id });
            }

            TaskModel task = new TaskModel();
            task = GetTasksById((int)taskid);

            if (task == null)
            {
                ErrorMessage = "Er bestaat geen taak onder dit nummer";
                return RedirectToAction("Details", "Team", new { id });
            }

            // Tasks may only be edited if these are still open for approval, and not set as done
            if (task.Done == TaskProgress.Finished || task.Approved != Constants.TaskStatus.New)
            {
                ErrorMessage = "Taken mogen alleen aangepast worden als deze nog open staan!";
                return RedirectToAction("Details", "Team", new { id });
            }

            return View(task);
        }

        // POST: Team/id/Edit/taskid
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TaskModel task, int id, int taskid)
        {
            if (!ModelState.IsValid)
            {
                ErrorMessage = "Form is niet geldig";
                return View();
            }

            try
            {
                UpdateTask(taskid, task.Name, task.Description);
            }
            catch (Exception exception)
            {
                ErrorMessage = $"An error occurred when updating the task. {exception.Message}";
                return RedirectToAction("Details", "Team", new { id });
            }

            SuccessMessage = "Taak aangepast!";
            return RedirectToAction("Details", "Team", new { id });
        }
        #endregion

        #region Finish
        // GET: Team/id/Finish/taskid
        public ActionResult Finish(int id, int? taskid)
        {
            // User must be logged in in order to finish a task
            if (!UserSession.IsLoggedIn())
            {
                ErrorMessage = "U moet ingelogd zijn om een taak af te vinken!";
                return RedirectToAction("Index", "Home");
            }

            User user = Session["user"] as User;

            // Tasks may only be finished by those in that team
            if (UserSession.GetAccessLevel() != AccessLevel.Normal || user.TeamId != id)
            {
                ErrorMessage = "Alleen teamleden mogen hun taken afvinken!";
                return RedirectToAction("Index", "Team");
            }

            if (taskid == null)
            {
                ErrorMessage = "Er is een taaknummer nodig om een taak af te kunnen vinken!";
                return RedirectToAction("Details", "Team", new { id });
            }

            TaskModel task = new TaskModel();
            task = GetTasksById((int)taskid);

            if (task == null)
            {
                ErrorMessage = "Er bestaat geen taak onder dit nummer";
                return RedirectToAction("Details", "Team", new { id });
            }

            // Tasks may only be finished if these are still open for approval, and not set as done
            if (task.Done == TaskProgress.Finished || task.Approved != Constants.TaskStatus.New)
            {
                ErrorMessage = "Taken mogen alleen afgevinkt worden als deze open staan!";
                return RedirectToAction("Details", "Team", new { id });
            }

            try
            {
                SetTaskFinished((int)taskid);
            }
            catch (Exception exception)
            {

SocialChallenge/Views/Team/Details.cshtml
@using Data
@using Data.DataForms
@using SocialChallenge.Methods
@model Data.DataForms.Team

<h1 class="text-center">@Model.Name</h1>
<h4 class="text-center">@String.Join(", ", Model.Users.Select(user => user.Fullname))</h4>

<br />

<p>
    @Html.ActionLink("Team info aanpassen", "edit", new { id = Model.Id })
    <br />
    @Html.ActionLink("Naar teams", "Index")
</p>

<hr />

<div class="text-center">
    <p>Taken volbracht: @Html.Raw(Model.Tasks.Count == 0 ? "nog geen taken!" : $"{Model.FinishedTasks.Count()} / {Model.Tasks.Count()}")</p>
    <p>Totale opbrengst: @Model.EarnString</p>
    @if (UserSession.IsLoggedIn() && UserSession.GetTeamId() == Model.Id)
    {
        <a href=@Url.Action("Revenuechange", "Task", new {Model.Id})><button class="btn btn-primary">Total opbrengst aanpassen</button></a>
    }
    else if (UserSession.IsLoggedIn() && UserSession.GetAccessLevel() != Constants.AccessLevel.Normal)
    {
        if (Model.Available == true)
        {
            <a href=@Url.Action("Delete", "Team", new {Model.Id})><button class="btn btn-danger">Team verwijderen</button></a>
        }
        else
        {
            <a href=@Url.Action("Recover", "Team", new {Model.Id})><button class="btn btn-success">Team herstellen</button></a>
        }
    }   
</div>

<h2>@Html.DisplayNameFor(model => model.Tasks)</h2>
@if (UserSession.IsLoggedIn() && UserSession.GetTeamId() == Model.Id)
{
    <a href=@Url.Action("Create", "Task", new {Model.Id})><button class="btn btn-primary">Nieuwe taak aanmaken</button></a>
    <br />
    <br />
}

@if (!Model.Tasks.Any())
{
    <div class="alert alert-warning" role="alert">
        Dit team heeft nog geen taken opgesteld.
    </div>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">@Html.DisplayNameFor(model => model.Tasks[0].Name)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.Tasks[0].Description)</th>
                <th scope="col" class="text-center">@Html.DisplayNameFor(model => model.Tasks[0].Done)</th>
                <th scope="col" class="text-center">@Html.DisplayNameFor(model => model.Tasks[0].Approved)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Task task in Model.Tasks)
            {
                @* add a success or error class depending on the task's approval setting *@
                <tr @Html.Raw(task.Approved == Constants.TaskStatus.Approved ? "class=\"success\"" : task.Approved == Constants.TaskStatus.Rejected ? "class=\"error\"" : "")>

                    <td>@task.Name</td>
                    <td>@task.Description</td>
                    <td class="text-center">
                        @Html.Raw(task.Done == Constants.TaskProgress.Finished ? "&#10004" : "")
                    </td>
                    <td class="text-center">
                        @Html.Raw(task.Approved == Constants.TaskStatus.Approved ? "&#10004" : task.Approved == Constants.TaskStatus.Rejected ? "X" : "")
                    </td>
                    <td>
                        @if (UserSession.IsLoggedIn() && UserSession.GetTeamId() == Model.Id)
                        {
                            // Edit button
                            if (task.Done == Constants.TaskProgress.Open && task.Approved == Constants.TaskStatus.New)
                            {
                                <a href=@Url.Action("Edit", "Task", new { id = Model.Id, taskid = task.Id })><button class="btn btn-primary">Aanpassen</button></a>
                            }

                            // If your team has a task open that you can set as done, make a button
                            if (task.Done == Constants.TaskProgress.Open && task.Approved == Constants.TaskStatus.New)
                            {
                                <a href=@Url.Action("Finish", "Task", new { id = Model.Id, taskid = task.Id })><button class="btn btn-success">Afvinken</button></a>
                            }
                        }

                        @if (UserSession.IsLoggedIn() && UserSession.GetAccessLevel() != Constants.AccessLevel.Normal)
                        {
                            // Approve button
                            if (task.Approved != Constants.TaskStatus.Approved && task.Done == Constants.TaskProgress.Finished)
                            {
                                <a href=@Url.Action("Approve", "Task", new { id = Model.Id, taskid = task.Id })><button class="btn btn-success">Goedkeuren</button></a>
                            }

                            // Reject button (should always be visible if not rejected yet, because of stupid tasks)
                            if (task.Approved != Constants.TaskStatus.Rejected)
                            {
                                <a href=@Url.Action("Reject", "Task", new { id = Model.Id, taskid = task.Id })><button class="btn btn-danger">Afkeuren</button></a>
                            }

                            // A revert button to revert a task approval that was not done
                            if (task.Approved != Constants.TaskStatus.New)
                            {
                                <a href=@Url.Action("Revert", "Task", new { id = Model.Id, taskid = task.Id })><button class="btn btn-default">terugkeren</button></a>
                            }
                        }

                    </td>
                </tr>
            }
        </tbody>
    </table>
}

<small class="text-muted">Een taak is pas volbracht als deze goedgekeurd is door een docent.</small>
@if (Model.Charitygoal == null)
{
    <br />
    <small class="text-muted">Dit team heeft nog geen doelbedrag.</small>
}

SocialChallenge/Views/Team/Edit.cshtml
@model Data.DataForms.Team

@{
    ViewBag.Title = "Aanpassen";
}

<h2 class="text-center">@ViewBag.Title</h2>
<h4 class="text-center">Pas hier de info van je team aan.</h4>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Charitygoal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Charitygoal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Charitygoal, "", new { @class = "text-danger" })
                <br/>
                <small class="text-muted">Als je je doelbedrag nog niet weet, hoef je deze nog niet in te vullen.</small>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Aanpassen" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Terug naar je team", "Details", new {Model.Id})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SocialChallenge/Views/Team/Index.cshtml
@using Data.DataForms
@model IEnumerable<Data.DataForms.Team>

@{
    ViewBag.Title = "Teams";
}

<h2>Teams</h2>

@if (!Model.Any())
{
    <div class="alert alert-warning" role="alert">
        Er zijn nog geen teams.
    </div>
}
else
{
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Users)
            </th>
        </tr>

        @foreach (Team team in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(team.Name, "Details", new {id = team.Id})
                </td>
                <td>
                    @Html.Raw(String.Join(", ", team.Users.Select(
                        s => string.Format(
                            "<a href="+Url.Action("profile", "home", new { id = s.Id, referral = "teams" })+">{0}</a>", s.Fullname)
                    )))
                </td>
            </tr>
        }

    </table>
}