SocialChallenge/Controllers/CodesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using SocialChallenge.Methods;

using Data.DataForms;
using static Data.Constants;

// Data Access libraries
using static DataLibrary.Logic.CodeProcessor;
using static DataLibrary.Logic.TeamProcessor;

// Main model
using CodeModel = Data.DataForms.Code;

// Client model
using ClientCodeModel = Data.CreateForms.Code;

namespace SocialChallenge.Controllers
{
    public class CodeController : BaseController
    {
        #region Index
        // GET: Codes/
        public ActionResult Index()
        {
            if (!UserSession.IsLoggedIn() || UserSession.GetAccessLevel() != AccessLevel.Admin)
            {
                ErrorMessage = "Je bent niet bevoegd voor deze pagina.";
                return RedirectToAction("Index", "Home");
            }

            List<CodeModel> codes = new List<CodeModel>();

            try
            {
                codes = GetCodes();
            }
            catch (Exception exception)
            {
                ErrorMessage = $"An error occurred receiving all codes. {exception.Message}";
            }

            return View(codes);
        }
        #endregion

        #region Create
        // POST: Codes/
        [HttpPost]
        [ActionName("Index")]
        public ActionResult CreateNewCode()
        {
            List<CodeModel> codes = new List<CodeModel>();

            try
            {
                codes = GetCodes();
            }
            catch (Exception exception)
            {
                ErrorMessage = $"An error occurred receiving all codes. {exception.Message}";
            }

            string teamString = Request.Form["teamid"];

            // teamid may only be digits
            if (!teamString.All(c => c >= '0' && c <= '9'))
            {
                ErrorMessage = "Teamid mag alleen uit een nummer bestaan!";
                return View(codes);
            }

            int? teamId = String.IsNullOrEmpty(teamString) ? (int?) null : Convert.ToInt32(teamString);
            AccessLevel level = Request.Form["teacher-code"] != null ? AccessLevel.Teacher : AccessLevel.Normal;

            string shareCode;
            try
            {
                shareCode = CreateCode(level, level == AccessLevel.Normal ? teamId : null);
            }
            catch (Exception exception)
            {
                ErrorMessage = $"Something went wrong when creating a new code. {exception.Message}";
                return View();
            }

            // Add the new code to the list so it's viewed with the rest
            codes.Add(new Code {
                Id = shareCode,
                Access_level = level,
                TeamId = teamId,
                Use_By = DateTime.Now.AddDays(level == AccessLevel.Normal ? StudentCodeDayLimit : TeacherCodeDayLimit)
            });

            // Check if a team should be created
            bool newTeamCreated = false;
            if (teamId != null)
            {
                Team team = new Team();
                try
                {
                    team = LoadTeamByTeamId((int)teamId);
                }
                catch (Exception exception)
                {
                    ErrorMessage = $"Something went wrong when checking for existing team. {exception.Message}";
                    return View();
                }

                if (team == null)
                {
                    try
                    {
                        CreateTeam($"Team{teamId}", teamId);
                    }
                    catch (Exception exception)
                    {
                        ErrorMessage = $"Something went wrong when creating a team for the user. {exception.Message}";
                        return View();
                    }

                    newTeamCreated = true;
                }
            }

            SuccessMessage = $"De nieuwe code is aangemaakt! {(newTeamCreated ? "Er is ook een team aangemaakt. " : "")}<u>Geef deze aan de gebruiker om te registreren!</u><br/>De code kan je hieronder vinden.";
            InfoMessage = shareCode;
            return View(codes);
        }
        #endregion

        #region Show
        // POST: Codes/Show/id
        public ActionResult Show(string id)
        {
            if (!UserSession.IsLoggedIn() || UserSession.GetAccessLevel() != AccessLevel.Admin)
            {
                ErrorMessage = "Je bent niet bevoegd voor deze pagina.";
                return RedirectToAction("Index", "Home");
            }

            return Content(id);
        }
        #endregion
    }
}

SocialChallenge/Controllers/HomeController.cs
using System.Web.Mvc;

// Data Access libraries
using static DataLibrary.Logic.UserProcessor;

// Main model
using UserModel = Data.DataForms.User;

// Client model
using ClientUserModel = Data.CreateForms.User;

namespace SocialChallenge.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        // GET: Profile
        public ActionResult Profile(int? id, string referral)
        {
            // An id is required for the controller method to work
            if (id == null)
            {
                ErrorMessage = "Profiel vereist een id van een user!";
                return RedirectToAction("Index", "User");
            }

            UserModel user = new UserModel();

            // Referral link
            ViewBag.referral = referral;

            // Load the user
            user = LoadUserById((int)id);

            // If user id is 0 nothing was returned
            if (user == null)
            {
                ErrorMessage = "Gebruiker bestaat niet!";
                return RedirectToAction("Index", "User");
            }

            return View(user);
        }
    }
}

SocialChallenge/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SocialChallenge.Methods;

using Data;
using static Data.Constants;

// Data Access libraries
using static DataLibrary.Logic.UserProcessor;
using static DataLibrary.Logic.CodeProcessor;
using static DataLibrary.Logic.TeamProcessor;

// Main model
using UserModel = Data.DataForms.User;
using CodeModel = Data.DataForms.Code;
using TeamModel = Data.DataForms.Team;

// Client model
using ClientUserModel = Data.CreateForms.User;
using ClientTeamModel = Data.CreateForms.Team;

namespace SocialChallenge.Controllers
{
    public class UserController : BaseController
    {
        #region Index
        // GET: User/
        public ActionResult Index()
        {
            if (!UserSession.IsLoggedIn() || UserSession.GetAccessLevel() == AccessLevel.Normal)
            {
                ErrorMessage = "Je bent niet bevoegd voor deze pagina.";
                return RedirectToAction("Index", "Home");
            }

            List<UserModel> users = new List<UserModel>();

            try
            {
                users = LoadUsers();
            }
            catch (Exception exception)
            {
                ErrorMessage = $"An error occurred. {exception.Message}";
            }

            // Remove all users that have been removed when not admin
            if (Session["user"] == null || (Session["user"] as UserModel).Access_level != AccessLevel.Admin)
            {
                users = users.Where(user => user.Status != StatusType.Removed).ToList();
            }

            return View(users);
        }
        #endregion

        #region SignUp
        // GET: User/Signup
        public ActionResult SignUp()
        {
            // If you're already logged in there's no need to try and register
            if (UserSession.IsLoggedIn())
            {
                ErrorMessage = "Log uit voordat je een nieuwe registratie aanmaakt.";
                return RedirectToAction("index");
            }

            // Get the usercount for the registrationcode
            // No users means no registrationcode is needed the first time
            try
            {
                ViewBag.userCount = CountUsers();
            }
            catch (Exception exception)
            {
                ErrorMessage = $"Something went wrong when grabbing total usercount. {exception.Message}";
                return View();
            }
            
            return View();
        }

        // POST: User/Signup
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignUp(ClientUserModel user)
        {
            if (!ModelState.IsValid)
            {
                ErrorMessage = "Form is niet geldig";
                return View();
            }

            // Load all users beforehand. If we received 0, this is the first user and he will get full account access
            int? userCount;
            try
            {
                userCount = CountUsers();
            }
            catch (Exception exception)
            {
                ErrorMessage = $"Something went wrong when grabbing total usercount. {exception.Message}";
                return View();
            }

            // If a team is made for this user since there was none, this turns true.
            // It means that in the end, you will be prompted with another screen to set your team name
            bool firstTeamMember = false;
            string teamName = "";

            // Firstly confirm the registrationcode is valid when not the first signup. If it is we will receive the teamid and access_level
            // Set the accesslevel to admin by default. This is changed with the code, and it wont when no code is available, always making the first person admin
            AccessLevel accessLevel = AccessLevel.Admin;
            int? teamId = null;
            TeamModel team = new TeamModel();

            // If the team we load later is unavailable, this bool with turn true
            bool TeamIsUnavailable = false;

            if (userCount != 0)
            {
                if (user.Code == null)
                {
                    ErrorMessage = "Voer een geldige registratiecode in.";
                    return View();
                }

                CodeModel code = GetCodeById(user.Code);

                if (code == null)
                {
                    ErrorMessage = "Ongeldige registratiecode";
                    return View();
                }

                if (code.Use_By <= DateTime.Now)
                {
                    ErrorMessage = "Deze code kan niet meer gebruikt worden is ongeldig.";
                    return View();
                }

                // Maximum of 5 users can sign up with the same code
                if (code.Users != null && code.Users.Count >= 5)
                {
                    ErrorMessage = "Deze code is al 5 keer gebruikt en mag niet meer gebruikt worden.";
                    return View();
                }

                // Update the access level and teamid
                accessLevel = code.Access_level;
                teamId = code.TeamId;

                // The first registered teammember can change some team info if he wants
                if (teamId != null)
                {
                    try
                    {
                        team = LoadTeamByTeamId((int)teamId);
                    }
                    catch (Exception exception)
                    {
                        ErrorMessage = $"Something went wrong when checking the team for any existing users. {exception.Message}";
                        return View();
                    }

                    // If the signup is the first signup of the page, notify the user later on with this bool
                    if (team.Users.Count == 0 && team.Available)
                    {
                        firstTeamMember = true;
                    }

                    // If the team is unavailable/removed, set teamId to null and set a bool so we tell the user
                    if (!team.Available)
                    {
                        teamId = null;
                        TeamIsUnavailable = true;
                    }
                }
            }

            EncryptedPassword encryptedPassword = Password.HashAndSalt(user.Password);
            int lastId;

            try
            {
                lastId = CreateUser(user.Username, user.Firstname, user.Insertion, user.Lastname, encryptedPassword.HashedPassword, encryptedPassword.Salt, accessLevel, teamId);
            }
            catch (Exception exception)
            {
                // Check if the username is already in use, and inform the user
                if (exception.Message.Contains("Duplicate entry"))
                {
                    ErrorMessage = $@"Gebruiker ""{user.Username}"" bestaat al.";
                }
                else
                {
                    ErrorMessage = exception.Message;
                }

                return View();
            }

            // Add the user to the used code's userId's
            if (userCount != 0)
            {
                try
                {
                    AddUserIdtoCode(user.Code, lastId);
                }
                catch (Exception exception)
                {
                    ErrorMessage = $"Something went wrong when adding the user to the code's userIds. {exception.Message}";
                    return View();
                }
            }

            // Set the user in a session to log him in.
            Session["user"] = LoadUserById(lastId);

            string message = "Gebruiker aangemaakt en ingelogd!";

            // Notify the user he got admin access due to being the first signup
            if (userCount == 0)
            {
                message +=
                    "<br/>Omdat dit de eerst geregistreerde gebruiker is op de site, heeft deze admin toegangkelijkheid gekregen.";
            }

            // Notify the user the team is unavailable/removed
            if (TeamIsUnavailable)
            {
                message +=
                    "<br/>Het team gebonden aan deze code is helaas verwijderd. Vraag een docent voor een nieuw team.";
            }

            SuccessMessage = message;

            // If a new team was made for this user, we will load a tab for setting the team name, rather than redirecting to the previous page
            if (firstTeamMember)
            {
                return RedirectToAction("SetNewTeamInfo");
            }

            return RedirectToAction("Index", "Home");
        }
        #endregion

        #region Login
        // GET: User/Login
        public ActionResult Login()
        {
            // If you're already logged in there's no need to try again
            if (UserSession.IsLoggedIn())
            {
                ErrorMessage = "Je bent al ingelogd!";
                return RedirectToAction("index");
            }

            return View();
        }

        // POST: User/Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(ClientUserModel user)
        {
            string errormessage = "Ongeldig gebruikersnaam of wachtwoord.";

            // Get the user based on the username, and encrypt the password so we can compare those
            UserModel dbUser = LoadUserByUsername(user.Username);

            // No user returned
            if (dbUser == null)
            {
                ErrorMessage = errormessage;
                return View();
            }

            // Password doesn't match
            if (!Password.Confirm(user.Password, dbUser.PasswordHash, dbUser.Salt))
            {
                ErrorMessage = errormessage;
                return View();
            }

            // User has been removed

SocialChallenge/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SocialChallenge/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SocialChallenge/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

SocialChallenge/Views/Home/Profile.cshtml
@using Data
@using SocialChallenge.Methods
@model Data.DataForms.User

@{
    ViewBag.Title = "Profiel";
}

<div>
    <div class="text-center">
        <h1>(@Model.Id) @Model.Username</h1>

        @if (Model.Access_level == Constants.AccessLevel.Teacher)
        {
            <h4>Docent</h4>
        }
        else if (Model.Access_level == Constants.AccessLevel.Admin)
        {
            <h4>Website administrator</h4>
        }
    </div>
    
    <br/>
    <p>
        @{ bool canEdit = false; }

        @* If the user is logged in, there could be an edit, remove and recover button if the user has the right privileges *@
        @if (UserSession.IsLoggedIn())
        {
        @* If the user is an admin there will be buttons if he's not viewing himself *@
            if (UserSession.GetAccessLevel() == Constants.AccessLevel.Admin)
            {
                @Html.ActionLink("Aanpassen", "Edit", "User", new { id = Model.Id }, null)

            @* An admin cannot remove/recover himself *@
                if (UserSession.GetId() != Model.Id)
                {
                    @Html.Raw(" - ");
                    if (Model.Status == Constants.StatusType.Normal)
                    {
                        @Html.ActionLink("Verwijderen", "Delete", "User", new { id = Model.Id }, null)
                    }
                    else
                    {
                        @Html.ActionLink("Herstellen", "Recover", "User", new { id = Model.Id }, null)
                    }
                }

                canEdit = true;
            }

        @* A regular user may only edit himself *@
            else if (UserSession.GetId() == Model.Id)
            {
                @Html.ActionLink("Aanpassen", "Edit", "User", new { id = Model.Id }, null)
                canEdit = true;
            }
        }

        @if (canEdit && !String.IsNullOrEmpty(ViewBag.referral))
        {
            @Html.Raw(" - ");
        }

        @if (!String.IsNullOrEmpty(ViewBag.referral))
        {
            if (ViewBag.referral == "list")
            {
                @Html.ActionLink("Terug naar gebruikers", "Index", "User")
            }
            else if (ViewBag.referral == "teams")
            {
                @Html.ActionLink("Terug naar teams", "Index", "Team")
            }
            else if (ViewBag.referral == "codes")
            {
                @Html.ActionLink("Terug naar codes", "Index", "Code")
            }
        }
    </p>

    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fullname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fullname)
        </dd>

        @if (Model.Access_level == Constants.AccessLevel.Normal)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Team)
            </dt>

            <dd>
                @if (Model.Team == null)
                {
                    @Html.Raw("gebruiker bevind zich niet in een team.")
                }
                else
                {
                    @Html.ActionLink(Model.Team.Name, "Details", "Team", new { id = Model.Team.Id }, null)
                }
            </dd>
        }

        <dt>
            Account leeftijd
        </dt>

        <dd>
            @{ int dayDifference = (DateTime.Now - Model.Date_added).Days; }
            @Html.Raw($"{dayDifference} {(dayDifference == 1 ? "dag" : "dagen")}")
        </dd>
    </dl>
</div>